### ISSUE TITLE
build.zig:11:11: error: unused local constant

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [ityonemo/zigler#286]
```
== Compilation error in file lib/tg2.ex ==
** (CompileError)  this zig compiler warning hasn't been incorporated into the parser.
Please file a report at:
https://github.com/ityonemo/zigler/issues
C:\Users\CHARLE~1\AppData\Local\Temp\.zigler_compiler\dev\Elixir.TG2\build.zig:11:11: error: unused local constant

    (zigler 0.8.1) lib/zig/parser/error.ex:54: Zig.Parser.Error.parse/2
    (zigler 0.8.1) lib/zig/command.ex:34: Zig.Command.compile/2
    (zigler 0.8.1) lib/zig/compiler.ex:107: Zig.Compiler.compilation/2
    (zigler 0.8.1) expanding macro: Zig.Compiler.__before_compile__/1
    lib/tg2.ex:1: TG2 (module)
```

Maybe we comment this line out for now...
https://github.com/ityonemo/zigler/blob/74b4be78e6b9377447fceb86318159d75d827e36/lib/zig/builder.ex#L22

**Comment by ityonemo** [comment]
https://github.com/ityonemo/zigler/issues/292

**Comment by ityonemo** [comment]
fixed here:  https://github.com/ityonemo/zigler/commit/46ae9c32b061fb5fb33f6d794926ed2b98ba14b5
