### ISSUE TITLE
zigler doesn't detect that zig has been cached in the zig directory of "deps"

### ISSUE THREAD

**Issue by ityonemo** [ityonemo/zigler#59]
results in this error:

** (CompileError) lib/zigler_test.ex:1: zig hasn't been downloaded.  Run mix zigler.get_zig 
    expanding macro: Zigler.Compiler.__before_compile__/1
    lib/zigler_test.ex:1: ZiglerTest (module)
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

**Comment by ityonemo** [comment]
fixed in https://github.com/ityonemo/zigler/pull/60/commits/9fc95cf76ccbba0d737f3a672079b202fd30b191
